package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies extends TestBase {
    /*
    Class: Day09_Cookies
    Method: handleCookies
    -Go to amazon  and automate the tasks:
    1. Find the total number of cookies
    2. Print all the cookies
    3. Get the cookies by their name
    4. Add new cookie
    5. Delete cookie by name
    6. Delete all the cookies
    /*
Cookies are temporary data that is generated by browser.
It's the way for a website to remember you, your preferences and you habits on web.
 */
        @Test
        public void cookieTest() throws InterruptedException {
//        -Go to amazon  and automate the tasks:
            driver.get("https://www.amazon.com");

//        1. Find the total number of cookies
            Set<Cookie> allCookies = driver.manage().getCookies();
            int numOfCookies = allCookies.size();
            System.out.println("Number Of Cookies : "+numOfCookies);//Mine is 7

//        2. Print all the cookies
            for (Cookie eachCookie : allCookies){
                System.out.println("Cookie ==>>> "+eachCookie);
                System.out.println("Cookie Value ===>>> "+eachCookie.getValue());
                System.out.println("Cookie Name ===>>> "+eachCookie.getName());
            }

//        3. Get the cookies by their name
            System.out.println("Cookie Named : "+
                    driver.manage().getCookieNamed("i18n-prefs"));
            //Cookie cookieNamed=driver.manage().getCookieNamed("i18n-prefs");
            //System.out.println("cookieNamed = " + cookieNamed);
            //entering cookie name and getting the entire cookie

//        4. Add new cookie
            Cookie cookie = new Cookie("my-fav-cookie","apple-pie");
            driver.manage().addCookie(cookie);
            Thread.sleep(2000);
            Set<Cookie> newCookies = driver.manage().getCookies();
            System.out.println("New Number Of Cookie ===>>> "+
                    newCookies.size());//1 more than original number of cookie

//        5. Delete cookie by name
            driver.manage().getCookieNamed("session-id");
            int lastNumberOfCookies = driver.manage().getCookies().size();
            System.out.println("Last Number of Cookies after delete===>>> "+
                    lastNumberOfCookies);//8

//        6. Delete all the cookies
            driver.manage().deleteAllCookies();
            int finalNumberOfCookies = driver.manage().getCookies().size();
            System.out.println("Final Number Of cookies ===>>> "+
                    finalNumberOfCookies);//0
        }
    }

